### ISSUE TITLE
To-do for v0.1

### ISSUE THREAD

**Issue by Survingo** [Survingo/LuckyBlockWars#1]
- [x] More customizable
- [] Bug fixes (if there're any bugs)
- [] More stuff for Lucky Blocks
- [] Easy to understand and to use
- [] Comment the source code

**Comment by Survingo** [comment]
unobtrusively... :clap: :P

**Comment by Adam1609** [comment]
No bugs, need more stuff for LuckyBlock, and really have to publish this plugin

**Comment by Survingo** [comment]
You've tested the plugin, @Adam1609? I thought there'll be some bugs. Anyways, you're right. Also I need to add a multi-arena-system.

**Comment by Adam1609** [comment]
Yes, I have tested! No bug, smoothly running and very cool though. But do you have stone as luckyblock? Because old plugin, when i mine the stone, it drops leather boots

**Comment by Survingo** [comment]
The luckyblock is customizable via the config.yml. For default its 19 (sponge) but I haven't added armor drops (yet)

**Comment by Pav155** [comment]
Add on the list reset map and countdown please.
